version: '3.9'
services:
    db:
        image: postgres:alpine
        ports:
            - 3001:5432
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${PASSWORD}
            - POSTGRES_USERNAME=${USERNAME}
            - POSTGRES_DB=${DATABASE_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data
    app:
        build: .
        ports:
            - 3000:3000
        depends_on:
            - db
volumes:
    postgres-data:






